[package]
name = "suiDex"
edition = "legacy" 


[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "devnet" }


[addresses]
suidex = "0x0"



